name: CI

on: [push]

jobs:
  build-macOS-latest:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run `sh setup.sh`
      run: |
        sh setup.sh
  # build-ubuntu-latest:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Run ./setup.sh
  #     run: |
  #       ./setup.sh
  # build-ubuntu-16-04:
  #   runs-on: ubuntu-16.04
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Run ./setup.sh
  #     run: |
  #       ./setup.sh
#     - name: Run macos setup.sh
#       run: |
#         ./macos/setup.sh
#     - name: Run tmux setup.sh
#       run: |
#         ./tmux/setup.sh
#     - name: Run zsh setup.sh
#       run: |
#         # yes command causes long execution in container 
#         ./zsh/setup.sh
